---
title: "Assignment2 Whanganui Property Rates"
author: "John Lavack 20001249"
date: "2026-08-09"
output: html_document
---

```{r attach libs,warning = FALSE, message = FALSE}
library(tidygraph)
library(tidyverse)
library(readxl)
library(ggdist)
library(waffle)
#remotes::install_github("hrbrmstr/waffle", dependencies = FALSE) - cran sometimes silently fails.

```

```{r read in data, message = FALSE}
#data in Draft Rates by property 26.27 - statistical purposes 1 in two sheets. Data and Unit Rates

Data <- read_excel("Draft Rates by property 26.27 - statistical purposes 1.xlsx", sheet = "Data", skip = 2) %>% drop_na(property_no) #first two rows are blank, Can map headers from unit_rates reference data set. Last rows are totals, but totals have no property number, so drop. 
Unit_Rates <- read_excel("Draft Rates by property 26.27 - statistical purposes 1.xlsx", sheet = "Unit Rates")
wdc_rates <- read_csv("wdc_rates_qv.csv") %>% mutate(rate_yr = factor(rate_yr, levels = c("22_23", "23_24", "24_25", "25_26", "26_27"), ordered = TRUE))
```

```{r}
wdc_rates %>% filter(property_no == 6318)
```

```{r color palette notes}

 "#6190F7"
 "#DC0100"
 "#69A241"
 "#FEC30E"
```


```{r}
Data %>% filter( property_no == 13) %>% select(where(~!all(is.na(.))))
# sum of {CBD rates, UAGC, General Rates, Water Rates, Stormwater, Firefighting capacity, Roading, Wastewater, Earthquake, Kerbside, Forestry, Roading Resilience, Trade Waste} = total
# AND sum of {CBD, CBDA, CBD, ESC, ESF, ESR, GC1, GCS, GFA10, GFA3, GFA4, GFA5, GR1, GRA1, GRA2, GRA5, GRS, KS, MAW, MAWD, MAWR, RDA, RDAS, RDB, RDBS, RDF, RRC, RRF, RRR, SD, SDO, SDOS, SMO, SMOH, SRWV1, SRWV2, UAGC, WC, WCM, WFC, WS, WSH, WSRE, WWS, FE, TWCOD, TWFlow, TWTSS, TWWWTP} = total. 
# first set of sums have conditional rules that look along row 2 (where unit rates names are above the columns in set 2), checks which match the column headers in the first set, then sums the columns. It is a classification hierarchy grouping process. So, column BQ is for CBD rates, the sum looks for all columns in the group `CBD Rates` then sums only those. Of which there are three: CBD, CBDA and CBDB. Same deal for all the others. 

# The requirement is a 2 page flyer. Therefore, expect 2- 4 graphics. Try 2 simpler ones and 2 more complex ones.  
# 1. Which areas have the highest rates over time? OR which areas have the highest change this time?: a map of whanganui with heat colors. 
# Can show areas with QV average for area and rates average per area to eyeball if higher = higher or not.   
# 2. What contributes the most to rates increases this year, using data and the unit rates to look at the contributing components of each rate element.
#    find the max column, then reshape to get property no, value, contirbuting rate code, then the hierarchy it belongs to. And % contribution to rate increase. Can also look at the aggregate part too... could be fun. 
# 3. Look at rates variances 
# 4 land area changes or land usage changes and impact on rates. Perhaps I can color in the map or look at suburbs and their split of qv_categories vs rates changes over time. i.e. increase in commerical and larger increase in rates? Will play with that. 
# Lead with a gimme: how rates have changed over time in whanganui. the year on year % change overall. As a lead in. 
# Fan chart 
```
# Graph 1 and 2 - time

```{r graph 1 -spaghetti pct change}
# rates over time, need to set a factor order for the rate_yr, OR map them to years. 
#will now try group by property number then calculate the year on year percentage change, 

graph_1_data <- wdc_rates %>%
  arrange(property_no, rate_yr) %>%
  group_by(property_no) %>%
  mutate(pct_change = (`total rates` - lag(`total rates`)) / lag(`total rates`) * 100,
         pct_change = replace_na(pct_change, 0)) %>%
  ungroup() %>%
  select(property_no, rate_yr, `total rates`, pct_change) %>%
  filter(property_no != 6318) #remove outlier

graph_1_summary <- graph_1_data %>% 
  group_by(rate_yr) %>%
  summarise(median_pct = median(pct_change),
            mean_pct = mean(pct_change),
            .groups = 'drop')
  
#spaghetti plot
#property 6318 has a 13464.58% rates change. That is odd. I will drop it. A commerical property that was increasedd from42 to 5710 in 24_25
graph_1 <- graph_1_data %>% 
ggplot(aes(x = rate_yr, y = pct_change, group = property_no)) +
  geom_line(col = "#6190F7", alpha = 0.15, linewidth = 0.2) +
  geom_line(data = graph_1_summary, aes(x = rate_yr, y = median_pct, group = 1), col = "#DC0100", linewidth = 1) +
  theme(legend.position = 'none')

# I think this is pretty good for a start, maybe trim out more outliers so audience can see the pct change around the median. 
```

```{r}
graph_1
```






```{r graph 2 - fan chart pct change}
graph_2_data <- graph_1_data %>%
  # filter(pct_change < 100) %>%
  group_by(rate_yr) %>%
  summarise(
    median = median(pct_change),
    mean = mean(pct_change),
    lower25 = quantile(pct_change, 0.375),
    upper25 = quantile(pct_change, 0.625),
    lower50 = quantile(pct_change, 0.25),
    upper50 = quantile(pct_change, 0.75),
    lower90 = quantile(pct_change, 0.05),
    upper90 = quantile(pct_change, 0.95),
    lower100 = quantile(pct_change, 0),
    upper100 = quantile(pct_change, 1),
  )

graph_2 <- ggplot(data = graph_2_data, aes(x = rate_yr, group = 1)) +
  # geom_ribbon(aes(ymin = lower100, ymax = upper100), fill = "#6190F7", alpha = 0.2) +
  geom_ribbon(aes(ymin = lower90, ymax = upper90, fill = "90%"), alpha = 0.4) +
  geom_ribbon(aes(ymin = lower50, ymax = upper50, fill = "50%"), alpha = 0.6) +
  geom_ribbon(aes(ymin = lower25, ymax = upper25, fill = "25%"), alpha = 0.9) +
  geom_line(aes(y=median, color = "Median change"), linewidth = 1) +
  theme_minimal() +
  scale_fill_manual(
  name = "Qunatiles",
  values = c("90%" = "#6190F7", 
             "50%" = "#6190F7", 
             "25%" = "#6190F7")
  ) + 
  scale_color_manual(
    name = "Estimates",
    values = c("Median change" = "#DC0100")
  ) +
  theme(legend.position = "top",
      plot.title = element_text(size = 17),
      plot.subtitle = element_text(size = 13),
      axis.title.y = element_text(size = 13),
      axis.title.x = element_text(size = 13))

graph_2

#may want ot note the property revaluation that occured in 2022 and impacted 23/24
  
```

```{r graph 3 map setup}
#Taking this from lab04
library(maps)    
library(sf)  

nz <- read_sf("https://www.massey.ac.nz/~jcmarsha/data/nz_map/sa3_data.sqlite")

```

# Graph 3 - Map

```{r graph 3 map, fig.width=10, fig.height= 10}
ta_nz <- nz %>% 
  group_by(territorial_authority, regional_council) %>%
  summarise(geometry = st_union(GEOMETRY), .groups = 'drop')

whanganui <- nz %>% filter(territorial_authority == "Whanganui District")
bbox <- st_bbox(whanganui)

# w_bbox <- list(x = c(1751098, 1815702), x=c(5565628, 5655993))

w_bbox <- list(x = c(1767500, 1779000), y=c(5574000, 5585000))

```

```{r}
#I need to map wdc_rates to Sa3_name, then calculate the fill of the map geom as the average rate value... how can I sohw this through time... maybe a facet wrap? 
# group by suburb, then summarise the rates by suburb, then left join rates to the map data, then plot. That's the process. 
sort(unique(wdc_rates$suburb))
paste("break:")
sort(unique(whanganui$sa3_name))
paste("break:")
sort(unique(graph_3_data$suburb))
```

```{r, fig.width=10, fig.height=10}
#getting the streets int he suburbs. To then go map to suburbs manually. 

#what to do about st john and otamtea? I may try mapping streets to the releavant suburb. Will split the string to get street then google search I guess. 
St_John_Streets <- c('Acton Pl', 'Aiken Rd', 'Alexa Pl', "Brassey Rd","Bristow St", "Chittick Pl","Collier Pl", "Dickson Cres", "Halswell St","Halswell Street","Hillside Tce", "Kent Rd","Linda Pl", "Ngapuhi St", "Oakland Ave","Parkes Ave", "Parsons St", "Porritt St", "Rawhiti Pl", "Smart Tce", "St Leonard St","Taranaki St","Tarata St", "Tregarth St","Tulloch St", "Virginia Rd", 'Peakes Rd', 'Victoria Park', 'Virginia Lake (Rotokawau)')

Otamatea_Streets <- c('Sewerage Pump Turere', 'Babbage Pl', 'Beachcroft', "Chelsea Cl", "Cotswolds Cl", "Diana Pl", "Eaton Cres", "Edith Collier Dr", "Edmonds Dr", "Goldsbury Pl", "Gumtree Rise", "Holdsworth Dr", "Kawau Pl", "Lancewood Pl", "Lithgow Dr", "Mannington Rd", "Montgomery Rd", "Norfolk Dr", "Otamatea Reserve", "Perrett Dr", "Pickwick Rd", "Rotokawau Dr", "Sandcroft Dr", "Sandy Lane", "St Johns Hts", "Suffolk Dr", "Tasman Views", "Tirimoana Pl", "Turere Pl","Virginia Hts", "Webster Pl", "Pukeko Drive", 'Tangaroa View', 'Middens Way')

Springvale_streets <-c('Addenbrooke Tce')

Whanganui_Centre_Streets <- c('Pitt St', 'Peat Pl', 'Peat St')
#great north road spans both. Lower number in St Johns up to 117. Then 119 and 121 are St Johns. 118, 120 and 122 onwards are otamtea



streets <- wdc_rates %>% 
  filter(suburb == "St Johns/Otamatea") %>% 
  select(property_no, rate_yr, property_address, suburb) %>%
  mutate(
    house_num = as.integer(str_extract(property_address, "^\\s*(\\d+)")), 
    street = str_remove(property_address, "~.*"),
    street = str_remove(street, "-."),
    street = str_remove(street, "^(?i:unit\\s+)?(?:[\\d/][\\d/A-Za-z]*\\s+)+"), #handles numbers and numbers like 9A,alos UNIT 6C / 59 and
  ) %>%
  mutate(
    suburb = case_when(
      #house numbers on great north road
      street == "Great North Rd" & is.na(house_num) ~ "St Johns Hill",
      street == "Great North Rd" & house_num <= 117 ~ "St Johns Hill",
      street == "Great North Rd" & house_num %in% c(119, 121) ~ "St Johns Hill",
      street == "Great North Rd" & house_num >= 118 ~ "Otamatea (Whanganui District)",
      #easier ones
      street %in% St_John_Streets ~ "St Johns Hill",
      street %in% Otamatea_Streets ~ "Otamatea (Whanganui District)",
      street %in% Springvale_streets ~ "Springvale",
      street %in% Whanganui_Centre_Streets ~ "Whanganui Centre",
      TRUE ~ suburb
    )
  ) %>% select(property_no, rate_yr, suburb) #for left join

#move this to earlier step for data wrangling after reading in. Except the summarise bit. Just the suburb remapping
graph_3_data <- wdc_rates %>% 
  left_join(streets, by = c('property_no', 'rate_yr'), suffix = c("", "_new")) %>%
  mutate(suburb = coalesce(suburb_new, suburb)) %>%
  mutate(
    suburb = recode(suburb,
    "Bastia/Durie Hills Putiki" = "Bastia-Durie Hill-Putiki",
    "Whanganui Central" = "Whanganui Centre",
    "Whanganui Rural" = "Whanganui District Rural",)
  ) %>%
  select(-suburb_new) %>% 
  group_by(suburb) %>%
  summarise(median_rates = median(`total rates`, .groups = 'drop'))

whanganui %>%
  left_join(graph_3_data, by = c('sa3_name' = 'suburb')) %>%
  ggplot() +
  geom_sf(mapping=aes(fill = median_rates), col = 'white', alpha = 0.5) +
  coord_sf(xlim = w_bbox$x, ylim = w_bbox$y) + #need to change the rural district label to be visible
  geom_sf_label(mapping=aes(label=sa3_name), size=3)+
  annotate("label", x = 1777000, y = 5584000,
           label = "Whanganui District Rural", size = 3, fill = 'white') + #play with this to get the piosition right
  scale_fill_gradientn(colors = c( "#69A241", "#6190F7", "#FEC30E", '#DC0100'),
                       limits = c(min(graph_3_data$median_rates), max(graph_3_data$median_rates))) +
  theme_minimal()

  # guides(fill = median_rates)
# w_bbox <- list(x = c(1767500, 1779000), y=c(5574000, 5585000))


```

```{r}
wdc_rates %>% filter(`total rates` > 25000) %>% filter(`qv category` == 'Residential') %>%
  ggplot() +
  geom_density(aes(x = `total rates`))
```

#Graph 4 - qv category

```{r, fig.height=10, fig.width=10}
# for one graph I will show, with the density eye plot the categorical density of rates by qv category. As they vary heaps
# lots of categories, maybe too many. I'll try mapping them ot the Data res/com/faarm ones ot get a clearer graph
widths = c(0.5, 0.8, 0.95)

#identify outliers by category, then also plot them on the graph., Use a simple IQR method

wdc_rates %>% filter(!is.na(`qv category`) ) %>%
  # filter(`qv category` %in% c('Residential')) %>%
  mutate(outlier = `total rates` < quantile(`total rates`, 0.25) - 1.5 * IQR(`total rates`) |
           `total rates` > quantile(`total rates`, 0.75) + 1.5 * IQR(`total rates`)) %>%
  filter(!outlier) %>%
  ggplot(aes(x = `total rates`, y = `qv category`)) +
  # stat_interval(.width = widths, alpha=0.4) +
  stat_halfeye(
    mapping = aes(fill_ramp = after_stat(level)), 
    fill_type = "segments", 
    .width = widths, 
    # alpha = 0.5, 
    show.legend = FALSE,
    col = 'darkgray'
  ) +
  stat_interval(.width = widths, position = position_nudge(y = -0.05)) +
  stat_summary(geom = "point", fun = median, col = 'black', position = position_nudge(y = -0.05)) +
  scale_fill_ramp_discrete(na.translate = FALSE) +
  theme_minimal() +
    scale_color_manual(values = c("#FEC30E","#6190F7", "#69A241")) 



 # "#6190F7"
 # "#DC0100"
 # "#69A241"
 # "#FEC30E"

#copied code from assignment 1
# # +
#   geom_vline(xintercept = mean_value, col = 'black', lty = 'dashed') +
#   #add an annotation over hte y axis ot indicate the number of sites
#   annotate("text", 
#            x = 0, # Position x near the counts (right side)
#            y = y_levels[5], # Position y at the top-most category level
#            label = "(Sites, Samples)", 
#            size = 3, 
#            hjust = 1.2, # Left align the header with the counts
#            vjust = -3, # Push it up above the label
#            family = "mono") +
#   #group mean annotation
#   annotate("text", 
#            x = 2, # Position x near the counts (right side)
#            y = y_levels[5], # Position y at the top-most category level
#            label = paste0('pooled mean = ', round(mean_value, 2)), 
#            size = 3, 
#            hjust = -0.1, # keep it to the right of the mean line
#            vjust = -7, # Push it up over the geom
#            family = "mono") +
#   scale_y_discrete(labels = label_lookup) + #applying the custom labels 
#   #colors go outside in
#   scale_color_manual(values = c("#f9e4c4","#79b9e7", "#4277af")) + 
#   scale_x_continuous(breaks= seq(0, max(plot_data$`Clarity (BDISC)`), by = 1)) +
#   coord_cartesian(xlim = c(0, 12), clip = "off") +
#   labs(
#     title = 'Is oversampling bias making rivers less clear?',
#     subtitle = 'No, but increased activity around rivers does',
#     caption = "Pasture land and urban areas have mean water clarity below the pooled mean, despite high or low sample sites \n while native forests are above it. There appears to be no trend in altitude. \n Sampled sites are all between Wellington and Palmerston in NZ",
#     x = 'Water clarity (Meters of depth visibility)', 
#     y = '') +
#   theme_lawa() 
```



# Graph 5 - rate contributor
```{r rates breakdown, fig.width=10, fig.height=10}

#so waffle chart didn't work out. I will do a tree map instead.
library(treemap)


#the rates variance % is wrong in this data set... someone cocked up.
# this needs to go in an inintail data cleaning step 
Data %>% select(property_no, LV:Difference ) %>% 
  filter(`2025/26 Rates` > 0) %>%
  mutate(`Rates Variance %` = (`Rates Variance $` / `2025/26 Rates` * 100 )) %>%
  arrange(desc(`Rates Variance %`)) %>% 
  filter(!is.na(`Rates Variance %`)) %>% summarise(median(`Rates Variance %`))

#So this looks pretty good, I will need ot map the righ suburbs to it. Could try a cock comb chart?
graph_4_data <- Data %>% 
  select(property_no, `Res/ Comm/ Faarm`, `Land Use`, Suburb, `CBD rates`:total ) %>%
  pivot_longer(
    cols = `CBD rates`:total,
    names_to =  'rate_type',
    values_to = 'value'
  ) %>%
  filter(rate_type != 'total') %>%
  # filter(Suburb == 'Springvale') %>%
  group_by(Suburb,rate_type) %>%
  summarise(value = sum(value), .groups = 'drop') 

  treemap(
    graph_4_data,
    index = c("Suburb", "rate_type"),
    vSize = "value",
    vColor = 'rate_type',
    type = "index",
    palette = "Set2",
    title = 'Rates by Suburb'
  )
```


